compress_assets: off
gzip_assets: off
package_path: ../build/www/
javascripts:

  all:
   - assets/www/js/main.js
   - assets/www/js/menu.js
   - assets/www/js/info.js
   - assets/www/js/jquery.jflip.js

  vendor:
    - assets/www/js/vendor/*.js  
    - assets/www/js/phonegap/ios/*.js
    
stylesheets:
  main:
    - assets/www/css/main.css
    - assets/www/css/flip.css
  low:
    - assets/www/css/low.css
  middle:
    - assets/www/css/middle.css
  high:
    - assets/www/css/high.css