compress_assets: on
gzip_assets: off
package_assets: off
package_path: ../assets/www/gen
javascripts:

  all:
   - assets_src/js/*.js

  libs:
    - assets_src/js/vendor/*.js
  phonegap:
    - assets_src/js/phonegap/ios/*.js