compress_assets: on
gzip_assets: off
package_path: ../assets/www/javascripts
javascripts:

  delta-all:
   - assets-src/javascripts/app/demo.js
   - assets-src/javascripts/app/common.js
   - assets-src/javascripts/app/constants.js
   - assets-src/javascripts/app/routes.js
   - assets-src/javascripts/app/app.js
   - assets-src/javascripts/app/locale.js
   - assets-src/javascripts/app/locales/*.js
   - assets-src/javascripts/app/views/**/*.js
   - assets-src/javascripts/app/models/*.js
   - assets-src/javascripts/app/controllers/*.js
   - assets-src/javascripts/app/lib/*.js


  plugins-all:
    - assets-src/javascripts/android/phonegap-1.0.0.js
    - assets-src/javascripts/android/EmailComposer.js
    - assets-src/javascripts/android/fileDownload.js
    - assets-src/javascripts/android/fileuploader.js
    - assets-src/javascripts/android/multiAudioPlayer.js
    - assets-src/javascripts/android/ChildBrowser.js
